final/config/routes.rb
Rails.application.routes.draw do

resources :firstyears

root to: "firstyears#index"

resources :meetings

end

final/app/models/case.rb
class Case < ActiveRecord::Base
  has_many :meetings
  belongs_to :case_source
end

final/app/models/case_source.rb
class CaseSource < ActiveRecord::Base
  has_many :cases
end

final/app/models/firstyear.rb
class Firstyear < ActiveRecord::Base
  has_many :meetings
end

final/app/models/meeting.rb
class Meeting < ActiveRecord::Base
	belongs_to :firstyear 
  belongs_to :secondyear
  belongs_to :case
end

final/app/models/second_year.rb
class SecondYear < ActiveRecord::Base
  has_many :meetings
end

final/app/controllers/cases_controller.rb
class CasesController < ApplicationController

	def index
		@cases = Case.all
	end

	def show
		@case = Case.find_by(id: params["id"])
		@roles = Role.where(movie_id: @movie.id)
		@actors = []
		@roles.each do |role|
			the_actor = Actor.find_by(id: role.actor_id)
			@actors << the_actor
		end
	end

end

final/app/controllers/final_controller.rb
class FinalController < ApplicationController
end

final/app/controllers/firstyears_controller.rb
class FirstyearsController < ApplicationController 

  def index 
  	@firstyears = Firstyear.all 
  end 

  def new
    @firstyear = Firstyear.new 
  end 

  def show 
    @firstyear = Firstyear.find_by(id: params["id"])
        @meetings = Meeting.where(meeting_id: @firstyear.id)
    @cases = []
    @meetings.each do |meeting|
    @cases << Case.find_by(id: meeting.firstyear_id)
    end 	
  end 

  def create
    firstyear_params = params.require(:firstyear).permit(:first_name, :last_name)
    Firstyear.create(firstyear_params)
    redirect_to firstyears_path
  end

  def edit 
    @firstyear = Firstyear.find_by(id: params["id"])
  end 

  def update
    firstyear_params = params.require(:firstyear).permit(:first_name, :last_name)
    @firstyear = Firstyear.find_by(id: params["id"])
    @firstyear.update(firstyear_params)
    redirect_to firstyears_path
  end 

  def destroy
    @firstyear = Firstyear.find_by(id: params["id"])
    @firstyear.destroy
    redirect_to firstyears_path
  end 

end 

final/app/controllers/meetings_controller.rb
class MeetingsController <ApplicationController 
   def index 
    @meetings = Meeting.all 
  end 

  def new
    @meeting = Meeting.new 
  end 

  def edit 
    @meeting = Meeting.find_by(id: params["id"])
  end 

  def create
    meeting_params = params.require(:meeting).permit!
    @meeting = Meeting.new(meeting_params)
    if @meeting.save
     redirect_to meetings_path
    else
      render text: "FAIL"
    end
  end

end 

final/app/views/cases/index.html.erb
<h1>Schedule your case!</h1>

final/app/views/final/index.html.erb
<h1>Schedule your case!</h1>

final/app/views/firstyears/edit.html.erb
<%= form_for @firstyear do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>
  <%= form.button 'Update First Year', class: "btn btn-success" %>
<% end %>

final/app/views/firstyears/index.html.erb
<h1 class="page-header">
  All First Years
  <span class="pull-right">
    <%= link_to "Add First Year", new_firstyear_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<table class="table">
  <% @firstyears.each do |firstyear| %>
    <tr>
    <td> <%= link_to firstyear.first_name + " "+firstyear.last_name, firstyear_path(firstyear) %> <%= link_to "Edit", edit_firstyear_path(firstyear) %> <%= link_to "Delete", firstyear_path(firstyear), method: :delete, data: { confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

final/app/views/firstyears/new.html.erb
<%= form_for @firstyear do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>
  <%= form.button 'Add First Year', class: "btn btn-success" %>
<% end %>

final/app/views/firstyears/show.html.erb
<h1><%= @firstyear.first_name %> <%= @firstyear.last_name %></h1>

<p>Email Address: <%= @firstyear.email_address %></p>
<p>Password: <%= @firstyear.password %></p>

final/app/views/meetings/index.html.erb
<h1 class="page-header">
 Meetings

final/app/views/meetings/new.html.erb
<!-- 
Finish the new page...

Movie:
  time: datetime
  firstyear: integer
  secondyear: integer
  case_id: integer
-->

<%= form_for @meeting do |form| %>
  <div class="form-group">
    <%= form.label :meeting_time %>
    <%= form.text_field :meeting_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :firstyear %>
    <%= form.text_field :firstyear, class: "form-control" %>
  </div>
  
   <div class="form-group">
    <%= form.label :secondyear %>
    <%= form.collection_select :secondyear, SecondYear.all, :id, :first_name, {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :case_id %>
    <%= form.collection_select :case_id, Case.all, :id, :title, {}, class: "form-control" %>
  </div>
  <%= form.button 'Create Meeting', class: "btn btn-success" %>
<% end %>